dataset: assist09
max_seq_length: 200
embed_path: embeddings/assist09_embedding.npz
epochs: 10 # maximum epochs 
learning_rate: 0.001
batch_size: 128 #训练的batch_size
tau: 1
sim: dot
n_layers: 2
n_heads: 2
hidden_size: 128
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: gelu
layer_norm_eps: 0.000000000001
initializer_range: 0.02
loss_type: CE